// Bu dersimizde modül ve paket mantığını anlamaya çalışacağız...
// Bu konu çoğu programlama dilinde aynıdır...
// Birbiriyle bağlantılı olan dosyaları bir paket haline getirir ve daha sonrasında işimize yarayan noktalarda kullanırız...
// import "fmt" yaptığımız zaman fmt.Println fonksiyonunu kullanabiliyoruz...
// Bu aşağıda gördüğünüz kodu bir paket haline getirip daha sonrasında tekrar nasıl çağrıldığına bakalım...
// demo1.go yu bu sayfada nasıl çağıracağız şimdi ona bakacağız...
// Bunun için modül eklememiz lazım. Peki bu nasıl yapılır hemen anlatıyorum...
// Önce terminale girip --> go mod init goLesson yazıyoruz...
// Burada mod modülün kısaltması, init initialize yani başlatmak demektir oradan gelir, goLesson ise sizin verdiğiniz ad olacaktır...
// import edeceğimiz şey ise goLesson yani kendi verdiğimiz isim / hangi folder'ın fonksiyonuna ulaşacaksak onun ismini yazıyoruz.
package main

import "goLesson/variables"

func main() {
	// fonksiyonu çağırırken ise folder.fonksiyon ismi() yapıyoruz.
	variables.Demo1()
}
